# Site settings
title: FCC Projects
baseurl: "/fcc-projects" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
githuburl: "https://franciscoknebel.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-71954823-8
disqus_shortname: fccprojects-fpk
